import Phaser from 'phaser';
import {UIScene,uiState} from './ui-scene';
import {profiles,selectProfile,uiLayout} from './ui-fixture';
import {MapScene,mapState} from './map-scene';
import {places,Place,MapMode,descriptions} from './map-fixture';
import {density,bufferSize} from './display';
const stage=document.querySelector<HTMLElement>('#stage')!,tools=document.querySelector<HTMLElement>('#tools')!;
let current:'ui'|'iso'=location.hash==='#iso'?'iso':'ui';
const initialDensity=current==='ui'?density():Math.min(2,density());
const initialSize=bufferSize(stage.clientWidth,stage.clientHeight,initialDensity);
const game=new Phaser.Game({type:Phaser.AUTO,parent:stage,backgroundColor:'#17232c',scale:{mode:Phaser.Scale.NONE,width:initialSize.width,height:initialSize.height,zoom:1/initialDensity},input:{activePointers:2},render:{antialias:true,roundPixels:false},scene:[],audio:{noAudio:true}});
let ready=false;
function note(value:string){document.querySelector('#announce')!.textContent=value;document.querySelector('#hint')!.textContent=value;}
function resizeCanvas(){stage.style.height=current==='ui'?uiLayout(stage.clientWidth).height+'px':'';const d=current==='ui'?density():Math.min(2,density());const size=bufferSize(stage.clientWidth,stage.clientHeight,d);game.scale.setZoom(1/d);game.scale.resize(size.width,size.height);}
function drawUI(){if(ready&&game.scene.isActive('ui'))(game.scene.getScene('ui') as UIScene).draw();}
function applyMap(){if(ready&&game.scene.isActive('iso'))(game.scene.getScene('iso') as MapScene).apply();}
function check(id:string,label:string,value:boolean){return `<label for="${id}">${label}<input id="${id}" type="checkbox" ${value?'checked':''}></label>`;}
function renderTools(){tools.innerHTML=current==='ui'?`<h2>Composants d’interface</h2><p>Une scène Phaser pour éprouver les futurs dossiers et commandes.</p><div class="group"><h3>Apparence</h3><label for="theme">Palette</label><select id="theme"><option value="night" ${uiState.theme==='night'?'selected':''}>Bureau de nuit</option><option value="paper" ${uiState.theme==='paper'?'selected':''}>Dossier papier</option></select>${check('large','Titres agrandis',uiState.large)}</div><div class="group"><h3>Valeurs de la fiche</h3>${['energy','xp','progress'].map((key,i)=>`<label class="range" for="ui-${key}"><span>${['Énergie','Expérience','Avancement de l’action'][i]}<output>${Math.round(uiState[key as 'energy'|'xp'|'progress'])} %</output></span><input id="ui-${key}" type="range" min="0" max="100" value="${uiState[key as 'energy'|'xp'|'progress']}"></label>`).join('')}<button id="animate-ui" class="full">${uiState.playing?'Pause':'Animer la progression'}</button></div><div class="group"><h3>États à tester</h3>${check('disabled','Action désactivée',uiState.disabled)}${check('busy','Personnage occupé',uiState.busy)}<button id="open-modal" class="full">Ouvrir la fenêtre</button></div><div class="group"><h3>Sélection accessible</h3><label for="person">Dossier</label><select id="person">${['Rose Bellini','Luca Moretti','Enzo Russo','Josephine Cole'].map((n,i)=>`<option value="${i}" ${i===uiState.selected?'selected':''}>${n}</option>`).join('')}</select></div><div class="info"><strong>Gym UI · 01</strong>Cartes, onglets, boutons et fenêtre sont dessinés dans Phaser. Ces commandes latérales pilotent le test.</div>`:
`<h2>Comparer les cartes</h2><p id="mode-description">${descriptions[mapState.mode]}</p><div class="group"><h3>Échelle de jeu</h3><label class="range" for="person-size"><span>Personnage <output>${mapState.personSize} unités</output></span><input id="person-size" type="range" min="32" max="88" step="4" value="${mapState.personSize}"></label><label class="range" for="street-width"><span>Largeur des rues <output>${mapState.streetWidth} unités</output></span><input id="street-width" type="range" min="72" max="140" step="4" value="${mapState.streetWidth}" ${mapState.mode==='old'?'disabled':''}></label><label class="range" for="zoom"><span>Zoom <output id="zoom-value">—</output></span><input id="zoom" type="range" min="18" max="250" value="100"></label><div class="row"><button id="zoom-out">−</button><button id="zoom-in">+</button></div></div><div class="group"><h3>Informations</h3>${check('labels','Noms et textes',mapState.labels)}${check('pois','Points d’intérêt',mapState.pois)}${check('people','Personnages de référence',mapState.people)}${check('path','Trajet témoin',mapState.path)}${check('xray','Façades transparentes',mapState.xray)}</div><div class="group"><h3>Inspecteur</h3><label for="lot-select">Lieu</label><select id="lot-select"><option value="">Choisir un lieu</option>${places.map(l=>`<option value="${l.id}" ${mapState.selected?.id===l.id?'selected':''}>${l.name}</option>`).join('')}</select><div id="lot-info" class="info">Touche un lieu ou un point d’intérêt.</div></div><div class="info"><strong>Même quartier, trois lectures</strong>Les nouveaux systèmes partagent six lieux et trois personnages. L’ancienne carte sert uniquement de référence. Les proportions et les tracés sont des données de test.</div>`;
 for(const key of ['energy','xp','progress'] as const)tools.querySelector('#ui-'+key)?.addEventListener('input',e=>{uiState[key]=Number((e.target as HTMLInputElement).value);uiState.playing=false;drawUI();syncUIValues();});tools.querySelector('#animate-ui')?.addEventListener('click',()=>{uiState.playing=!uiState.playing;syncUIValues();});
 tools.querySelectorAll<HTMLInputElement>('input[type=checkbox]').forEach(input=>input.addEventListener('change',()=>{if(current==='ui'){(uiState as unknown as Record<string,unknown>)[input.id]=input.checked;drawUI();}else{(mapState as unknown as Record<string,unknown>)[input.id]=input.checked;applyMap();}}));
 tools.querySelector('#theme')?.addEventListener('change',e=>{uiState.theme=(e.target as HTMLSelectElement).value as 'night'|'paper';drawUI();});
 tools.querySelector('#person')?.addEventListener('change',e=>{selectProfile(Number((e.target as HTMLSelectElement).value));drawUI();syncUIValues();});
 tools.querySelector('#open-modal')?.addEventListener('click',()=>{uiState.modal=true;drawUI();tools.classList.remove('open');document.querySelector('#tools-toggle')!.setAttribute('aria-expanded','false');});
 for(const [id,factor] of [['zoom-in',1.25],['zoom-out',.8]] as const)tools.querySelector('#'+id)?.addEventListener('click',()=>{const s=game.scene.getScene('iso') as MapScene;s.zoomTo(s.zoom*factor);});
 tools.querySelector('#fit')?.addEventListener('click',()=>{(game.scene.getScene('iso') as MapScene).fit();});
 tools.querySelector('#zoom')?.addEventListener('input',e=>(game.scene.getScene('iso') as MapScene).zoomTo(Number((e.target as HTMLInputElement).value)/100));
 tools.querySelector('#lot-select')?.addEventListener('change',e=>{const l=places.find(l=>l.id===(e.target as HTMLSelectElement).value);if(l)(game.scene.getScene('iso') as MapScene).select(l);});
 for(const [id,key] of [['person-size','personSize'],['street-width','streetWidth']] as const)tools.querySelector('#'+id)?.addEventListener('input',e=>{mapState[key]=Number((e.target as HTMLInputElement).value);const out=(e.target as HTMLInputElement).parentElement?.querySelector('output');if(out)out.textContent=mapState[key]+' unités';applyMap();});
 if(current==='iso'&&ready&&game.scene.isActive('iso')){zoomChanged((game.scene.getScene('iso') as MapScene).zoom);lotChanged(mapState.selected);}
}
function syncUIValues(){if(current!=='ui')return;for(const key of ['energy','xp','progress'] as const){const input=document.querySelector<HTMLInputElement>('#ui-'+key);if(input){input.value=String(uiState[key]);const out=input.parentElement?.querySelector('output');if(out)out.textContent=Math.round(uiState[key])+' %';}}const b=document.querySelector('#animate-ui');if(b)b.textContent=uiState.playing?'Pause':'Animer la progression';}
game.events.on('ui-values',syncUIValues);
function zoomChanged(z:number){const out=document.querySelector('#zoom-value'),slider=document.querySelector<HTMLInputElement>('#zoom');if(out)out.textContent=Math.round(z*100)+' %';if(slider)slider.value=String(z*100);}
function lotChanged(l:Place|null){const el=document.querySelector('#lot-info');if(el)el.innerHTML=l?`<strong>${l.name}</strong>Point d’intérêt : ${l.poi}<br>Emprise de test : ${l.w} × ${l.h}<br>Aucune règle économique.`:'Touche un lieu ou un point d’intérêt.';const sel=document.querySelector<HTMLSelectElement>('#lot-select');if(sel)sel.value=l?.id||'';const readout=document.querySelector('#map-selection');if(readout)readout.textContent=l?`${l.name} · ${l.poi}`:'Touche un lieu, un repère ou un personnage.';if(l)note(`${l.name} · ${l.poi}`);}
function switchGym(id:'ui'|'iso'){current=id;location.hash=id;document.querySelector<HTMLElement>('#map-controls')!.hidden=id!=='iso';document.body.classList.toggle('map-active',id==='iso');document.body.classList.toggle('ui-active',id==='ui');stage.style.height=id==='ui'?uiLayout(stage.clientWidth).height+'px':'';document.querySelectorAll<HTMLButtonElement>('[data-gym]').forEach(b=>{b.classList.toggle('active',b.dataset.gym===id);b.setAttribute('aria-pressed',String(b.dataset.gym===id));});document.querySelector('#title')!.textContent=id==='ui'?'Interface de gestion':'Laboratoire des cartes';document.querySelector('#eyebrow')!.textContent=id==='ui'?'GYM 01 / COMPOSANTS':'GYM 02 / VILLE';note(id==='ui'?'Choisis un dossier pour tester la sélection.':'Glisse pour explorer · pince pour zoomer · touche un bâtiment.');renderTools();if(ready){game.scene.stop(id==='ui'?'iso':'ui');resizeCanvas();game.scene.start(id);}}
game.events.once(Phaser.Core.Events.READY,()=>{game.scene.add('ui',UIScene);game.scene.add('iso',MapScene);ready=true;game.scene.start(current);document.querySelector('#loading')?.remove();});
game.events.on('zoom',zoomChanged);game.events.on('map-message',note);game.events.on('map-mode',(mode:MapMode)=>{document.querySelectorAll<HTMLButtonElement>('[data-mode]').forEach(b=>{b.classList.toggle('active',b.dataset.mode===mode);b.setAttribute('aria-pressed',String(b.dataset.mode===mode));});});game.events.on('map-scale',(v:{person:number;road:number})=>{document.querySelector('#map-scale')!.textContent=mapState.mode==='old'?`Personnage ≈ ${v.person}px · ancienne miniature`:mapState.mode==='plan'?'Plan schématique · pions à la place des silhouettes':`Personnage ≈ ${v.person}px · rue ≈ ${v.road}px à l’écran`;});game.events.on('lot',lotChanged);game.events.on('selection',(s:string)=>{note(s);const select=document.querySelector<HTMLSelectElement>('#person');if(select)select.value=String(uiState.selected);});
document.querySelectorAll<HTMLButtonElement>('[data-gym]').forEach(b=>b.addEventListener('click',()=>switchGym(b.dataset.gym as 'ui'|'iso')));
document.querySelector('#tools-toggle')!.addEventListener('click',()=>{const open=tools.classList.toggle('open');document.querySelector('#tools-toggle')!.setAttribute('aria-expanded',String(open));});
document.querySelector('#reset')!.addEventListener('click',()=>{if(current==='ui'){Object.assign(uiState,{theme:'night',large:false,selected:0,disabled:false,busy:true,modal:false,toast:'',tab:0,playing:false,sector:0,document:0});selectProfile(0);drawUI();}else{Object.assign(mapState,{labels:true,pois:true,people:true,path:true,xray:false,streetWidth:120,personSize:56,selected:null});const s=game.scene.getScene('iso') as MapScene;s.rebuild();s.playScale();}renderTools();note('Gym réinitialisé.');});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){uiState.modal=false;drawUI();tools.classList.remove('open');document.querySelector('#tools-toggle')!.setAttribute('aria-expanded','false');}});
window.addEventListener('resize',()=>{if(ready)resizeCanvas();});
window.addEventListener('hashchange',()=>{const id=location.hash==='#iso'?'iso':'ui';if(id!==current)switchGym(id);});
const observer=new ResizeObserver(()=>{if(ready)resizeCanvas();});observer.observe(stage);
setInterval(()=>{if(ready)document.querySelector('#metrics')!.textContent=`${Math.round(game.loop.actualFps)} FPS · ${stage.clientWidth} × ${stage.clientHeight}`;},700);
document.querySelectorAll<HTMLButtonElement>('[data-mode]').forEach(b=>b.addEventListener('click',()=>{if(!ready)return;const mode=b.dataset.mode as MapMode;(game.scene.getScene('iso') as MapScene).setMode(mode);renderTools();lotChanged(null);}));
document.querySelector('#play-scale')!.addEventListener('click',()=>{if(ready)(game.scene.getScene('iso') as MapScene).playScale();});
document.querySelector('#overview')!.addEventListener('click',()=>{if(ready)(game.scene.getScene('iso') as MapScene).fit();});
document.querySelector('#focus-person')!.addEventListener('click',()=>{if(ready)(game.scene.getScene('iso') as MapScene).focusPerson();});
switchGym(current);
