import Phaser from 'phaser';
import {UIScene,uiState} from './ui-scene';
import {MapScene,mapState} from './map-scene';
import {Lot,lots} from './iso';
const stage=document.querySelector<HTMLElement>('#stage')!,tools=document.querySelector<HTMLElement>('#tools')!;
let current:'ui'|'iso'=location.hash==='#iso'?'iso':'ui';
const game=new Phaser.Game({type:Phaser.AUTO,parent:stage,backgroundColor:'#17232c',scale:{mode:Phaser.Scale.RESIZE,width:stage.clientWidth,height:stage.clientHeight},input:{activePointers:2},render:{antialias:true,roundPixels:false},scene:[],audio:{noAudio:true}});
let ready=false;
function note(value:string){document.querySelector('#announce')!.textContent=value;document.querySelector('#hint')!.textContent=value;}
function drawUI(){if(ready&&game.scene.isActive('ui'))(game.scene.getScene('ui') as UIScene).draw();}
function applyMap(){if(ready&&game.scene.isActive('iso'))(game.scene.getScene('iso') as MapScene).apply();}
function check(id:string,label:string,value:boolean){return `<label for="${id}">${label}<input id="${id}" type="checkbox" ${value?'checked':''}></label>`;}
function renderTools(){tools.innerHTML=current==='ui'?`<h2>Composants d’interface</h2><p>Une scène Phaser pour éprouver les futurs dossiers et commandes.</p><div class="group"><h3>Apparence</h3><label for="theme">Palette</label><select id="theme"><option value="night" ${uiState.theme==='night'?'selected':''}>Bureau de nuit</option><option value="paper" ${uiState.theme==='paper'?'selected':''}>Dossier papier</option></select>${check('large','Titres agrandis',uiState.large)}</div><div class="group"><h3>États à tester</h3>${check('disabled','Action désactivée',uiState.disabled)}${check('busy','Personnage occupé',uiState.busy)}<button id="open-modal" class="full">Ouvrir la fenêtre</button></div><div class="group"><h3>Sélection accessible</h3><label for="person">Dossier</label><select id="person">${['Rose Bellini','Luca Moretti','Enzo Russo','Josephine Cole'].map((n,i)=>`<option value="${i}" ${i===uiState.selected?'selected':''}>${n}</option>`).join('')}</select></div><div class="info"><strong>Gym UI · 01</strong>Cartes, onglets, boutons et fenêtre sont dessinés dans Phaser. Ces commandes latérales pilotent le test.</div>`:
`<h2>Atelier de la ville</h2><p>Kit isométrique provisoire. Tester la lecture et la manipulation de la carte avant la direction artistique finale.</p><div class="group"><h3>Caméra</h3><div class="row"><button id="zoom-out" aria-label="Dézoomer">−</button><button id="fit">Cadrer</button><button id="zoom-in" aria-label="Zoomer">+</button></div><label class="range" for="zoom"><span>Zoom <output id="zoom-value">—</output></span><input id="zoom" type="range" min="18" max="250" value="50"></label></div><div class="group"><h3>Couches</h3>${check('grid','Grille de coordonnées',mapState.grid)}${check('labels','Noms des bâtiments',mapState.labels)}${check('buildings','Bâtiments',mapState.buildings)}${check('floors','Étages supplémentaires',mapState.floors)}${check('xray','Transparence',mapState.xray)}${check('plan','Vue en plan',mapState.plan)}</div><div class="group"><h3>Inspecteur</h3><label for="lot-select">Bâtiment</label><select id="lot-select"><option value="">Sélectionner sur la carte</option>${lots.map(l=>`<option value="${l.id}" ${mapState.selected?.id===l.id?'selected':''}>${l.x},${l.y} · ${l.name}</option>`).join('')}</select><div id="lot-info" class="info" style="margin-top:12px">Touche un bâtiment pour l’inspecter.</div></div><div class="group kbd"><b>Glisser</b><span>Déplacer la caméra</span><b>Pincer / molette</b><span>Zoomer</span><b>Toucher / cliquer</b><span>Sélectionner</span></div>`;
 tools.querySelectorAll<HTMLInputElement>('input[type=checkbox]').forEach(input=>input.addEventListener('change',()=>{if(current==='ui'){(uiState as unknown as Record<string,unknown>)[input.id]=input.checked;drawUI();}else{(mapState as unknown as Record<string,unknown>)[input.id]=input.checked;applyMap();}}));
 tools.querySelector('#theme')?.addEventListener('change',e=>{uiState.theme=(e.target as HTMLSelectElement).value as 'night'|'paper';drawUI();});
 tools.querySelector('#person')?.addEventListener('change',e=>{uiState.selected=Number((e.target as HTMLSelectElement).value);drawUI();});
 tools.querySelector('#open-modal')?.addEventListener('click',()=>{uiState.modal=true;drawUI();tools.classList.remove('open');document.querySelector('#tools-toggle')!.setAttribute('aria-expanded','false');});
 for(const [id,factor] of [['zoom-in',1.25],['zoom-out',.8]] as const)tools.querySelector('#'+id)?.addEventListener('click',()=>{const s=game.scene.getScene('iso') as MapScene;s.zoomTo(s.cameras.main.zoom*factor);});
 tools.querySelector('#fit')?.addEventListener('click',()=>{(game.scene.getScene('iso') as MapScene).fit();});
 tools.querySelector('#zoom')?.addEventListener('input',e=>(game.scene.getScene('iso') as MapScene).zoomTo(Number((e.target as HTMLInputElement).value)/100));
 tools.querySelector('#lot-select')?.addEventListener('change',e=>{const l=lots.find(l=>l.id===(e.target as HTMLSelectElement).value);if(l)(game.scene.getScene('iso') as MapScene).select(l);});
 if(current==='iso'&&ready&&game.scene.isActive('iso')){zoomChanged((game.scene.getScene('iso') as MapScene).cameras.main.zoom);lotChanged(mapState.selected);}
}
function zoomChanged(z:number){const out=document.querySelector('#zoom-value'),slider=document.querySelector<HTMLInputElement>('#zoom');if(out)out.textContent=Math.round(z*100)+' %';if(slider)slider.value=String(z*100);}
function lotChanged(l:Lot|null){const el=document.querySelector('#lot-info');if(el)el.innerHTML=l?`<strong>${l.name}</strong>Case ${l.x}, ${l.y} · ${mapState.floors?l.floors:1} étage(s)<br>Identifiant : ${l.id}<br>Donnée de test, sans activité économique.`:'Touche un bâtiment pour l’inspecter.';const sel=document.querySelector<HTMLSelectElement>('#lot-select');if(sel)sel.value=l?.id||'';if(l)note(`${l.name} · case ${l.x}, ${l.y}`);}
function switchGym(id:'ui'|'iso'){current=id;location.hash=id;document.querySelectorAll<HTMLButtonElement>('[data-gym]').forEach(b=>{b.classList.toggle('active',b.dataset.gym===id);b.setAttribute('aria-pressed',String(b.dataset.gym===id));});document.querySelector('#title')!.textContent=id==='ui'?'Interface de gestion':'Carte isométrique';document.querySelector('#eyebrow')!.textContent=id==='ui'?'GYM 01 / COMPOSANTS':'GYM 02 / VILLE';note(id==='ui'?'Choisis un dossier pour tester la sélection.':'Glisse pour explorer · pince pour zoomer · touche un bâtiment.');renderTools();if(ready){game.scene.stop(id==='ui'?'iso':'ui');game.scene.start(id);}}
game.events.once(Phaser.Core.Events.READY,()=>{game.scene.add('ui',UIScene);game.scene.add('iso',MapScene);ready=true;game.scene.start(current);document.querySelector('#loading')?.remove();});
game.events.on('zoom',zoomChanged);game.events.on('lot',lotChanged);game.events.on('selection',(s:string)=>{note(s);const select=document.querySelector<HTMLSelectElement>('#person');if(select)select.value=String(uiState.selected);});
document.querySelectorAll<HTMLButtonElement>('[data-gym]').forEach(b=>b.addEventListener('click',()=>switchGym(b.dataset.gym as 'ui'|'iso')));
document.querySelector('#tools-toggle')!.addEventListener('click',()=>{const open=tools.classList.toggle('open');document.querySelector('#tools-toggle')!.setAttribute('aria-expanded',String(open));});
document.querySelector('#reset')!.addEventListener('click',()=>{if(current==='ui'){Object.assign(uiState,{theme:'night',large:false,selected:0,disabled:false,busy:false,modal:false,toast:'',tab:0});drawUI();}else{Object.assign(mapState,{grid:false,labels:false,buildings:true,xray:false,floors:true,selected:null,plan:false});const s=game.scene.getScene('iso') as MapScene;s.highlight.clear();s.selectionLabel.setVisible(false);s.fit();s.apply();}renderTools();note('Gym réinitialisé.');});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){uiState.modal=false;drawUI();tools.classList.remove('open');document.querySelector('#tools-toggle')!.setAttribute('aria-expanded','false');}});
window.addEventListener('hashchange',()=>{const id=location.hash==='#iso'?'iso':'ui';if(id!==current)switchGym(id);});
const observer=new ResizeObserver(()=>{if(ready)game.scale.resize(stage.clientWidth,stage.clientHeight);});observer.observe(stage);
setInterval(()=>{if(ready)document.querySelector('#metrics')!.textContent=`${Math.round(game.loop.actualFps)} FPS · ${stage.clientWidth} × ${stage.clientHeight}`;},700);
switchGym(current);
