import Phaser from 'phaser';
import {places,actors,route,projectLab,MapMode,Place,descriptions} from './map-fixture';
import {lots,project,isRoad} from './iso';
import {density} from './display';
export const mapState={mode:'street' as MapMode,labels:true,pois:true,people:true,path:true,xray:false,streetWidth:120,personSize:56,selected:null as Place|null};
export class MapScene extends Phaser.Scene{
 private world!:Phaser.GameObjects.Container;private decor!:Phaser.GameObjects.Graphics;private overlay!:Phaser.GameObjects.Container;private labels:Phaser.GameObjects.Text[]=[];private people:Phaser.GameObjects.Container[]=[];private down={x:0,y:0,sx:0,sy:0};private dragged=false;private pinched=false;private distance=0;private pinchZoom=1;private keys?:Phaser.Types.Input.Keyboard.CursorKeys;private follow=false;private marker!:Phaser.GameObjects.Graphics;
 get d(){return Math.min(2,density());}get zoom(){return this.cameras.main.zoom/this.d;}
 constructor(){super('iso');}
 preload(){for(const k of ['road-x','road-y','cross','pavement','building-0','building-1','building-2','building-3','floor-brown','floor-red','person'])this.load.image(k,`./assets/${k}.${k==='person'?'webp':'png'}`);}
 create(){this.game.canvas.style.touchAction='none';this.input.manager.touch!.capture=true;this.input.manager.mouse!.preventDefaultWheel=true;this.input.on('pointerdown',(p:Phaser.Input.Pointer)=>{this.follow=false;this.down={x:p.x,y:p.y,sx:this.cameras.main.scrollX,sy:this.cameras.main.scrollY};this.dragged=false;this.pinched=this.active().length===2;if(this.pinched){this.distance=this.pinchDistance();this.pinchZoom=this.zoom;}});
 this.input.on('pointermove',(p:Phaser.Input.Pointer)=>{if(this.active().length===2){this.pinched=true;this.zoomTo(this.pinchZoom*this.pinchDistance()/Math.max(1,this.distance));return;}if(p.isDown&&!this.pinched){const dx=p.x-this.down.x,dy=p.y-this.down.y;if(Math.hypot(dx,dy)>7*this.d)this.dragged=true;if(this.dragged){this.cameras.main.scrollX=this.down.sx-dx/this.cameras.main.zoom;this.cameras.main.scrollY=this.down.sy-dy/this.cameras.main.zoom;}}});
 this.input.on('pointerup',(_p:Phaser.Input.Pointer,objects:Phaser.GameObjects.GameObject[])=>{if(this.dragged||this.pinched)return;const o=objects.find(o=>o.getData('place')||o.getData('actor'));if(o?.getData('place'))this.select(o.getData('place'));else if(o?.getData('actor')){this.follow=true;this.focusPerson();this.game.events.emit('map-message','Luca · personnage de référence, taille réglable.');}});
 this.input.on('wheel',(_p:unknown,_over:unknown,_dx:number,dy:number)=>this.zoomTo(this.zoom*(dy>0?.9:1.1)));
 this.keys=this.input.keyboard?.createCursorKeys();this.scale.on('resize',this.onResize,this);this.events.once('shutdown',()=>this.scale.off('resize',this.onResize,this));this.rebuild();this.playScale();}
 active(){return this.input.manager.pointers.filter(p=>p.isDown);}pinchDistance(){const p=this.active();return p.length>1?Phaser.Math.Distance.Between(p[0].x,p[0].y,p[1].x,p[1].y):0;}
 pos(x:number,y:number){return projectLab(x,y,mapState.mode);}
 placePos(l:Place){return {x:Math.sign(l.x)*(mapState.streetWidth/2+130),y:l.y};}
 polygon(points:{x:number;y:number}[],color:number,alpha=1,line?:number){const g=this.add.graphics();g.fillStyle(color,alpha);if(line)g.lineStyle(1,line);g.beginPath();points.forEach((p,i)=>i?g.lineTo(p.x,p.y):g.moveTo(p.x,p.y));g.closePath().fillPath();if(line)g.strokePath();this.world.add(g);return g;}
 rect(x:number,y:number,w:number,h:number,color:number,alpha=1,line?:number){return this.polygon([[x,y],[x+w,y],[x+w,y+h],[x,y+h]].map(([a,b])=>this.pos(a,b)),color,alpha,line);}
 label(x:number,y:number,value:string,color='#ebeadf',bg='#17252eee',size=14){const t=this.add.text(x,y,value,{fontFamily:'Arial',fontSize:`${size}px`,color,backgroundColor:bg,padding:{x:8,y:5},resolution:this.d}).setOrigin(.5,1);this.overlay.add(t);t.setData('fullLabel',value);this.labels.push(t);return t;}
 rebuild(){this.children.removeAll(true);this.labels=[];this.people=[];this.world=this.add.container(0,0);this.overlay=this.add.container(0,0).setDepth(2000);this.cameras.main.setBackgroundColor(mapState.mode==='plan'?0xe1dccb:0x223139);this.marker=this.add.graphics().setDepth(1900);
 if(mapState.mode==='old'){this.oldMap();return;}
 const sw=mapState.streetWidth;
 this.rect(-460,-380,920,1090,mapState.mode==='plan'?0xd1cebd:0x35434a);
 if(mapState.mode==='plan'){this.rect(-sw/2,-350,sw,1040,0xf3efdf);this.rect(-450,-sw/2,900,sw,0xf3efdf);this.rect(-450,315-sw/2,900,sw,0xf3efdf);}
 else{this.rect(-sw/2-18,-370,sw+36,1060,0x89918b);this.rect(-450,-sw/2-18,900,sw+36,0x89918b);this.rect(-450,315-sw/2-18,900,sw+36,0x89918b);this.rect(-sw/2,-370,sw,1060,0x263139);this.rect(-450,-sw/2,900,sw,0x263139);this.rect(-450,315-sw/2,900,sw,0x263139);
 for(let y=-320;y<680;y+=42)if(Math.abs(y)>sw/2+15&&Math.abs(y-315)>sw/2+15)this.rect(-1,y,2,16,0xc0b68a,.6);
 for(let x=-390;x<440;x+=42)if(Math.abs(x)>sw/2+15){this.rect(x,-1,16,2,0xc0b68a,.6);this.rect(x,314,16,2,0xc0b68a,.6);}}
 const roadName=this.pos(0,270);this.label(roadName.x,roadName.y,'AVENUE DU PORT',mapState.mode==='plan'?'#5f655b':'#a6b7bd',mapState.mode==='plan'?'#e1dccb':'#263139',11).setVisible(mapState.labels);
 if(mapState.path){const points=route.map(p=>this.pos(p.x,p.y));const g=this.add.graphics().lineStyle(4,0xe3b657,.8);g.beginPath();points.forEach((p,i)=>i?g.lineTo(p.x,p.y):g.moveTo(p.x,p.y));g.strokePath();this.world.add(g);}
 places.forEach(l=>{const c=this.placePos(l),p=this.pos(c.x,c.y);let hit:Phaser.GameObjects.GameObject;
 if(mapState.mode==='street'){this.rect(c.x-l.w/2-8,c.y-l.h/2-8,l.w+16,l.h+16,0x9ca18d,1);const im=this.add.image(p.x,p.y+58,`building-${l.kind}`).setOrigin(.5,1).setDisplaySize(l.w*1.4,l.w*1.4*127/132).setAlpha(mapState.xray?.28:1);this.world.add(im);im.setInteractive({pixelPerfect:true,alphaTolerance:60,useHandCursor:true});hit=im;}
 else{const r=this.add.rectangle(p.x,p.y,l.w,l.h,mapState.mode==='plan'?0xb7ac8e:0x687a7d).setStrokeStyle(2,mapState.mode==='plan'?0x877b5e:0xb4bdaf).setInteractive({useHandCursor:true});this.world.add(r);hit=r;if(mapState.mode==='top'){this.rect(c.x-l.w/2+8,c.y-l.h/2+8,l.w-16,l.h-16,0x45575e);this.rect(c.x-1,c.y-l.h/2+8,2,l.h-16,0x8c9b94);this.rect(c.x-l.w/2+8,c.y, l.w-16,2,0x8c9b94);}}
 hit.setData('place',l);
 const front=this.pos(c.x,c.y+(l.h/2)+10);const door=this.add.circle(front.x,front.y,5,0xf2ce80);this.world.add(door);
 const lp=this.pos(c.x,c.y+(l.h/2)+20);this.label(lp.x,lp.y+25,l.name,mapState.mode==='plan'?'#34382c':'#ebeadf',mapState.mode==='plan'?'#e9e4d4':'#17252eee').setVisible(mapState.labels);
 if(mapState.pois){const marker=this.pos(c.x,c.y-l.h/2-15);this.label(marker.x,marker.y,l.poi,'#18242b','#e1bb72',12).setInteractive({useHandCursor:true}).setData('place',l);}});
 this.addPeople();if(mapState.selected)this.select(mapState.selected,false);this.screenLabels();this.game.events.emit('map-mode',mapState.mode);}
 addPeople(){if(!mapState.people)return;actors.forEach((a,i)=>{const p=this.pos(a.x,a.y),c=this.add.container(p.x,p.y);this.overlay.add(c);const ground=this.add.ellipse(0,0,23,11,[0xf1c879,0x8dc6bc,0xc2d0d8][i],.8);const image=this.add.image(0,2,'person').setOrigin(.5,.93);const h=mapState.personSize;image.setDisplaySize(h*1122/1402,h);c.add([ground,image]);if(mapState.mode==='plan'){image.setVisible(false);ground.setSize(22,22);}const zone=this.add.zone(0,-h*.38,Math.max(38,h*.6),Math.max(44,h)).setInteractive({useHandCursor:true}).setData('actor',a.id);c.add(zone);this.people.push(c);if(mapState.labels)this.label(p.x,p.y-h-5,a.name,'#f2d491','#152530',13);});}
 oldMap(){for(let y=0;y<11;y++)for(let x=0;x<11;x++){const p=project(x,y),rx=x===3||x===7,ry=y===3||y===7;this.world.add(this.add.image(p.x,p.y,rx&&ry?'cross':rx?'road-y':ry?'road-x':'pavement').setOrigin(.5,1));}lots.forEach(l=>{const p=project(l.x,l.y);this.world.add(this.add.image(p.x,p.y,`building-${l.kind}`).setOrigin(.5,1));for(let f=1;f<l.floors;f++)this.world.add(this.add.image(p.x,p.y-42-f*32,l.kind<2?'floor-brown':'floor-red').setOrigin(.5,1));});if(mapState.people){const p=project(3,3),h=mapState.personSize;this.overlay.add(this.add.image(p.x,p.y-66,'person').setOrigin(.5,.93).setDisplaySize(h*.8,h));}this.game.events.emit('map-mode','old');}
 screenLabels(){const z=this.zoom;this.labels.forEach(t=>{t.setScale(1/z);const full=t.getData('fullLabel') as string;const place=places.find(l=>l.name===full);t.setText(z<.65&&place?place.short:full);});this.game.events.emit('map-scale',{person:Math.round(mapState.personSize*.84*z),road:Math.round(mapState.streetWidth*(mapState.mode==='street'?.734:1)*z)});}
 setMode(mode:MapMode){mapState.mode=mode;mapState.selected=null;this.follow=false;this.rebuild();this.playScale();this.game.events.emit('map-message',descriptions[mode]);}
 playScale(){const c=this.cameras.main;c.setZoom(this.d*(mapState.mode==='plan'?.8:1));const p=this.pos(0,50);c.centerOn(p.x,p.y-50);if(mapState.mode==='old'){this.fit();return;}this.screenLabels();this.game.events.emit('zoom',this.zoom);}
 fit(){const w=this.scale.width/this.d,h=this.scale.height/this.d,isIso=mapState.mode==='street',old=mapState.mode==='old';const z=Math.min(w/(old?1520:isIso?1650:1000),h/(old?880:isIso?950:1120));this.cameras.main.setZoom(this.d*Math.max(.18,z));const p=this.pos(0,160);this.cameras.main.centerOn(old?0:p.x,old?270:p.y);this.screenLabels();this.game.events.emit('zoom',this.zoom);}
 zoomTo(v:number){const c=this.cameras.main,center=c.getWorldPoint(this.scale.width/2,this.scale.height/2);c.setZoom(this.d*Phaser.Math.Clamp(v,.18,2.5));c.centerOn(center.x,center.y);this.screenLabels();this.game.events.emit('zoom',this.zoom);}
 focusPerson(){const p=this.pos(actors[0].x,actors[0].y);this.cameras.main.centerOn(p.x,p.y-45);this.game.events.emit('map-message','Luca au centre · compare sa taille à la rue.');}
 select(l:Place,emit=true){mapState.selected=l;const c=this.placePos(l),p=this.pos(c.x,c.y);this.marker.clear().lineStyle(3/this.zoom,0xf1c76f).strokeCircle(p.x,p.y,65);if(emit)this.game.events.emit('lot',l);}
 apply(){this.rebuild();}
 onResize(){this.playScale();}
 update(_t:number,dt:number){if(!this.keys)return;const c=this.cameras.main,step=Math.min(dt,50)*.6/this.zoom;if(this.keys.left.isDown)c.scrollX-=step;if(this.keys.right.isDown)c.scrollX+=step;if(this.keys.up.isDown)c.scrollY-=step;if(this.keys.down.isDown)c.scrollY+=step;}
}
