import Phaser from 'phaser';
import {project,unproject,isRoad,lots,Lot,TILE_W,TILE_H} from './iso';
export const mapState={grid:false,labels:false,buildings:true,xray:false,floors:true,selected:null as Lot|null,plan:false};
export class MapScene extends Phaser.Scene{
 houses:Phaser.GameObjects.Image[]=[];labels:Phaser.GameObjects.Text[]=[];grid!:Phaser.GameObjects.Graphics;highlight!:Phaser.GameObjects.Graphics;selectionLabel!:Phaser.GameObjects.Text;private down={x:0,y:0,sx:0,sy:0};private dragged=false;private pinched=false;private distance=0;private pinchZoom=1;private cursors?:Phaser.Types.Input.Keyboard.CursorKeys;
 constructor(){super('iso');}
 preload(){for(const key of ['road-x','road-y','cross','pavement','floor-brown','floor-red','building-0','building-1','building-2','building-3'])this.load.image(key,`./assets/${key}.png`);}
 create(){this.cameras.main.setBackgroundColor(0x182832);this.houses=[];this.labels=[];mapState.selected=null;
 for(let y=0;y<11;y++)for(let x=0;x<11;x++){const pos=project(x,y),rx=x===3||x===7,ry=y===3||y===7,key=rx&&ry?'cross':rx?'road-y':ry?'road-x':'pavement';this.add.image(pos.x,pos.y,key).setOrigin(.5,1).setDepth(-500+x+y);}
 lots.forEach(l=>{const p=project(l.x,l.y),depth=l.x+l.y;const base=this.add.image(p.x,p.y,`building-${l.kind}`).setOrigin(.5,1).setDepth(depth).setData('lot',l).setInteractive({pixelPerfect:true,alphaTolerance:50,useHandCursor:true});this.houses.push(base);
 for(let f=1;f<l.floors;f++){const extra=this.add.image(p.x,p.y-42-f*32,l.kind<2?'floor-brown':'floor-red').setOrigin(.5,1).setDepth(depth+f*.01).setData('lot',l).setData('extra',true).setInteractive({pixelPerfect:true,alphaTolerance:50,useHandCursor:true});this.houses.push(extra);}
 const label=this.add.text(p.x,p.y-138-(l.floors-1)*32,l.name,{fontFamily:'Arial',fontSize:'13px',backgroundColor:'#14212bee',padding:{x:7,y:5},color:'#d8dbcf'}).setOrigin(.5,1).setDepth(1000);this.labels.push(label);});
 this.grid=this.add.graphics().setDepth(500);this.highlight=this.add.graphics().setDepth(700);this.selectionLabel=this.add.text(0,0,'',{fontFamily:'Arial',fontSize:'16px',backgroundColor:'#d3b479',padding:{x:10,y:8},color:'#14212b'}).setOrigin(.5,1).setDepth(1100);
 this.input.addPointer(1);this.input.on('pointerdown',(p:Phaser.Input.Pointer)=>{this.down={x:p.x,y:p.y,sx:this.cameras.main.scrollX,sy:this.cameras.main.scrollY};this.dragged=false;if(this.activePointers().length===2){this.pinched=true;this.distance=this.pinchDistance();this.pinchZoom=this.cameras.main.zoom;}else this.pinched=false;});
 this.input.on('pointermove',(p:Phaser.Input.Pointer)=>{if(this.activePointers().length===2){this.pinched=true;const z=this.pinchZoom*this.pinchDistance()/Math.max(this.distance,1);this.zoomTo(z);return;}if(p.isDown&&!this.pinched){const dx=p.x-this.down.x,dy=p.y-this.down.y;if(Math.hypot(dx,dy)>7)this.dragged=true;if(this.dragged){this.cameras.main.scrollX=this.down.sx-dx/this.cameras.main.zoom;this.cameras.main.scrollY=this.down.sy-dy/this.cameras.main.zoom;}}});
 this.input.on('pointerup',(p:Phaser.Input.Pointer,objects:Phaser.GameObjects.GameObject[])=>{if(this.dragged||this.pinched)return;const lot=objects.find(o=>o.getData('lot'))?.getData('lot') as Lot|undefined;if(lot){this.select(lot);return;}const point=this.cameras.main.getWorldPoint(p.x,p.y),logical=unproject(point.x,point.y+66);const x=Math.round(logical.x),y=Math.round(logical.y);const found=lots.find(l=>l.x===x&&l.y===y);if(found)this.select(found);else if(x>=0&&x<11&&y>=0&&y<11){mapState.selected=null;this.highlight.clear();this.selectionLabel.setVisible(false);this.game.events.emit('lot',null);}});
 this.input.on('wheel',(_p:unknown,_over:unknown,_dx:number,dy:number)=>this.zoomTo(this.cameras.main.zoom*(dy>0?.9:1.1)));
 this.cursors=this.input.keyboard?.createCursorKeys();this.scale.on('resize',this.fit,this);this.events.once('shutdown',()=>this.scale.off('resize',this.fit,this));this.fit();this.apply();
 }
 activePointers(){return this.input.manager.pointers.filter(p=>p.isDown);}
 pinchDistance(){const p=this.activePointers();return p.length>1?Phaser.Math.Distance.Between(p[0].x,p[0].y,p[1].x,p[1].y):0;}
 fit(){const cam=this.cameras.main,z=Math.min(this.scale.width/(TILE_W*12),this.scale.height/(TILE_H*13));cam.setZoom(Math.max(.18,Math.min(z,1.2)));cam.centerOn(0,265);this.game.events.emit('zoom',cam.zoom);}
 zoomTo(value:number){const c=this.cameras.main,center=c.getWorldPoint(this.scale.width/2,this.scale.height/2);c.setZoom(Phaser.Math.Clamp(value,.18,2.5));c.centerOn(center.x,center.y);this.game.events.emit('zoom',c.zoom);}
 select(lot:Lot){mapState.selected=lot;const p=project(lot.x,lot.y);this.highlight.clear().lineStyle(3,0xf2cb75).fillStyle(0xeac279,.14);this.highlight.beginPath();this.highlight.moveTo(p.x,p.y-99);this.highlight.lineTo(p.x+66,p.y-66);this.highlight.lineTo(p.x,p.y-33);this.highlight.lineTo(p.x-66,p.y-66);this.highlight.closePath().fillPath().strokePath();this.selectionLabel.setPosition(p.x,p.y-145-(mapState.floors?(lot.floors-1)*32:0)).setText(lot.name).setVisible(true);this.game.events.emit('lot',lot);}
 apply(){this.houses.forEach(i=>{i.setVisible(mapState.buildings&&!mapState.plan&&(!i.getData('extra')||mapState.floors));i.setAlpha(mapState.xray?.32:1);});this.labels.forEach(l=>l.setVisible(mapState.labels));this.grid.clear();if(mapState.grid||mapState.plan){this.grid.lineStyle(1,0x93b4c0,mapState.plan?.65:.45);for(let y=0;y<11;y++)for(let x=0;x<11;x++){const p=project(x,y);this.grid.beginPath().moveTo(p.x,p.y-99).lineTo(p.x+66,p.y-66).lineTo(p.x,p.y-33).lineTo(p.x-66,p.y-66).closePath().strokePath();if(mapState.plan&&!isRoad(x,y)){this.grid.fillStyle(0xb2956d,.3).fillCircle(p.x,p.y-66,12);}}}if(mapState.selected)this.select(mapState.selected);}
 update(_time:number,delta:number){if(!this.cursors)return;const c=this.cameras.main,step=Math.min(delta,50)*.6/c.zoom;if(this.cursors.left.isDown)c.scrollX-=step;if(this.cursors.right.isDown)c.scrollX+=step;if(this.cursors.up.isDown)c.scrollY-=step;if(this.cursors.down.isDown)c.scrollY+=step;}
}
