import Phaser from 'phaser';
import {palettes,text,panel,button} from './theme';
export const uiState={theme:'night' as 'night'|'paper',large:false,selected:0,disabled:false,busy:false,modal:false,toast:'',tab:0};
const people=[{name:'Rose Bellini',role:'Lieutenante',frame:4},{name:'Luca Moretti',role:'Chauffeur',frame:1},{name:'Enzo Russo',role:'Homme de main',frame:0},{name:'Josephine Cole',role:'Comptable',frame:6}];
export class UIScene extends Phaser.Scene{
 constructor(){super('ui');}
 preload(){this.load.image('portraits','./assets/portraits.webp');}
 create(){const atlas=this.textures.get('portraits'),source=atlas.getSourceImage() as HTMLImageElement;for(let i=0;i<8;i++)if(!atlas.has(String(i)))atlas.add(String(i),0,(i%4)*source.width/4,Math.floor(i/4)*source.height/2,source.width/4,source.height/2);this.scale.on('resize',this.draw,this);this.events.once('shutdown',()=>this.scale.off('resize',this.draw,this));this.draw();}
 draw(){this.children.removeAll(true);const {width:w,height:h}=this.scale,p=palettes[uiState.theme];this.cameras.main.setBackgroundColor(p.bg);const pad=w<500?14:26,inner=w-pad*2,size=uiState.large?18:16,compact=w<640;
 text(this,pad,20,'FAMILLE RUSSO',compact?19:24,p.ink,true);text(this,pad,50,'Dossiers · échantillon d’interface',13,p.muted);text(this,w-pad,24,'LUNDI  /  08:00',12,p.muted).setOrigin(1,0);
 const cardW=(inner-9*3)/4,cardY=80,cardH=compact?108:136;
 people.forEach((person,i)=>{const x=pad+i*(cardW+9),selected=uiState.selected===i;const base=this.add.rectangle(x,cardY,cardW,cardH,p.panel).setOrigin(0).setStrokeStyle(selected?2:1,selected?p.gold:p.line).setInteractive({useHandCursor:true});base.on('pointerup',()=>{uiState.selected=i;this.draw();this.game.events.emit('selection',person.name);});const portraitSize=Math.min(cardW-14,compact?54:76);this.add.image(x+cardW/2,cardY+10+portraitSize/2,'portraits',String(person.frame)).setDisplaySize(portraitSize,portraitSize);text(this,x+cardW/2,cardY+portraitSize+19,person.name.split(' ')[0],compact?13:16,p.ink,true).setOrigin(.5,0);if(!compact)text(this,x+cardW/2,cardY+portraitSize+41,person.role,11,p.muted).setOrigin(.5,0);});
 const y=cardY+cardH+20,person=people[uiState.selected],panelH=Math.max(178,Math.min(260,h-y-72));panel(this,pad,y,inner,panelH,p);
 text(this,pad+16,y+16,person.name,size+3,p.ink,true);text(this,pad+16,y+43,person.role,13,p.muted);text(this,w-pad-16,y+20,uiState.busy?'OCCUPÉ':'DISPONIBLE',11,uiState.busy?'#c88a70':p.muted,true).setOrigin(1,0);
 const tabY=y+70,tabW=(inner-32)/3;['Dossier','Équipement','Ordres'].forEach((label,i)=>button(this,pad+16+i*tabW,tabY,tabW-6,label,()=>{uiState.tab=i;this.draw();},{selected:uiState.tab===i,p}));
 if(uiState.tab===0){text(this,pad+16,tabY+60,'Fiche de démonstration',size,p.ink,true);text(this,pad+16,tabY+86,compact?'Sélection, hiérarchie et lisibilité.':'Tester la sélection, la hiérarchie et la lisibilité des informations.',13,p.muted);}
 if(uiState.tab===1){text(this,pad+16,tabY+60,'Emplacements d’équipement',size,p.ink,true);text(this,pad+16,tabY+86,'Arme —     Véhicule —',14,p.muted);}
 if(uiState.tab===2){text(this,pad+16,tabY+60,uiState.busy?'Ordre de démonstration en cours':'Aucun ordre affecté',size,p.ink,true);text(this,pad+16,tabY+86,'La planification sera une prochaine boucle.',13,p.muted);}
 const bottom=Math.min(h-56,y+panelH+13),bw=(inner-10)/2;button(this,pad,bottom,bw,'Ouvrir une fenêtre',()=>{uiState.modal=true;this.draw();},{p});button(this,pad+bw+10,bottom,bw,'Tester une action',()=>{uiState.toast='Action reçue';this.draw();this.game.events.emit('selection','Action reçue');this.time.delayedCall(1500,()=>{uiState.toast='';if(this.scene.isActive())this.draw();});},{disabled:uiState.disabled,p,selected:true});
 if(uiState.toast){const toast=this.add.container(w/2,64);toast.add(this.add.rectangle(0,0,200,38,p.gold));toast.add(text(this,0,0,uiState.toast,15,'#1b2831',true).setOrigin(.5));}
 if(uiState.modal){const veil=this.add.rectangle(0,0,w,h,0x050b10,.7).setOrigin(0).setInteractive();void veil;const mw=Math.min(420,w-32),mh=225,mx=(w-mw)/2,my=(h-mh)/2;const c=this.add.container(mx,my);const back=this.add.rectangle(0,0,mw,mh,p.panel).setOrigin(0).setStrokeStyle(1,p.gold);const bar=this.add.rectangle(0,0,mw,48,p.line).setOrigin(0).setInteractive({draggable:true,useHandCursor:true});c.add([back,bar,text(this,16,15,'DOSSIER / FENÊTRE',14,p.ink,true),text(this,20,75,'Une fenêtre réutilisable',20,p.ink,true),text(this,20,111,'Déplace-la par sa barre de titre.',14,p.muted)]);const close=button(this,20,163,mw-40,'Fermer',()=>{uiState.modal=false;this.draw();},{p,selected:true});c.add(close);this.input.setDraggable(bar);let start={x:mx,y:my,px:0,py:0};bar.on('dragstart',(pointer:Phaser.Input.Pointer)=>{start={x:c.x,y:c.y,px:pointer.x,py:pointer.y};});bar.on('drag',(pointer:Phaser.Input.Pointer)=>{c.x=Phaser.Math.Clamp(start.x+pointer.x-start.px,0,w-mw);c.y=Phaser.Math.Clamp(start.y+pointer.y-start.py,0,h-mh);});}
 }
}
