import Phaser from 'phaser';
import {density} from './display';
import {palettes,text,panel,button} from './theme';
import {profiles,skillNames,uiState,selectProfile,uiLayout,clampPercent} from './ui-fixture';
import {meter,skill,actionPie,minimap,sectors} from './ui-widgets';
export {uiState} from './ui-fixture';
export class UIScene extends Phaser.Scene{
 private elapsed=0;
 constructor(){super('ui');}
 preload(){this.load.image('portraits','./assets/portraits.webp');}
 create(){const atlas=this.textures.get('portraits'),source=atlas.getSourceImage() as HTMLImageElement;for(let i=0;i<8;i++)if(!atlas.has(String(i)))atlas.add(String(i),0,(i%4)*source.width/4,Math.floor(i/4)*source.height/2,source.width/4,source.height/2);this.scale.on('resize',this.draw,this);this.events.once('shutdown',()=>this.scale.off('resize',this.draw,this));this.draw();}
 changed(){this.game.events.emit('ui-values');this.draw();}
 draw(){this.game.canvas.style.touchAction=uiState.modal?'none':'pan-y';this.input.manager.touch!.capture=uiState.modal;this.input.manager.mouse!.preventDefaultWheel=false;this.children.removeAll(true);const d=density(),w=this.scale.width/d,h=this.scale.height/d,p=palettes[uiState.theme],{compact,pad}=uiLayout(w),inner=w-pad*2,person=profiles[uiState.selected];this.cameras.main.setZoom(d).centerOn(w/2,h/2).setBackgroundColor(p.bg);
 text(this,pad,18,'DOSSIERS DE LA FAMILLE',compact?17:23,p.ink,true);text(this,w-pad,23,'GYM / DONNÉES FICTIVES',10,p.muted).setOrigin(1,0).setVisible(!compact);
 const cw=(inner-24)/4;profiles.forEach((a,i)=>{const x=pad+i*(cw+8),y=55;this.add.rectangle(x,y,cw,86,p.panel).setOrigin(0).setStrokeStyle(i===uiState.selected?2:1,i===uiState.selected?p.gold:p.line).setInteractive({useHandCursor:true}).on('pointerup',(pointer:Phaser.Input.Pointer)=>{if(pointer.getDistance()>10*d)return;selectProfile(i);this.changed();this.game.events.emit('selection',a.name);});this.add.image(x+cw/2,y+30,'portraits',String(a.frame)).setDisplaySize(44,44);text(this,x+cw/2,y+61,a.name.split(' ')[0],12,p.ink,true).setOrigin(.5,0);});
 panel(this,pad,157,inner,131,p);this.add.image(pad+46,204,'portraits',String(person.frame)).setDisplaySize(62,70);text(this,pad+91,172,person.name,uiState.large?22:19,p.ink,true);text(this,pad+91,201,person.role,14,p.muted);text(this,pad+91,224,person.alias,12,p.muted);text(this,pad+15,262,uiState.busy?`EN MISSION · ${person.location}`:'DISPONIBLE · au bureau',12,uiState.busy?'#c99471':p.muted,true);
 meter(this,pad,304,inner,'ÉNERGIE',uiState.energy,uiState.energy<25?0xc87868:0x74aaa0,p);
 const tw=inner/3;['Profil','Activité','Dossiers'].forEach((label,i)=>button(this,pad+i*tw,357,tw-6,label,()=>{uiState.tab=i;this.draw();},{p,selected:uiState.tab===i}));
 const columnW=compact?inner:(inner-24)/2,rx=compact?pad:pad+columnW+24,contentY=418;
 if(uiState.tab===0){text(this,pad,contentY,'COMPÉTENCES',12,p.muted,true);skillNames.forEach((label,i)=>skill(this,pad,contentY+29+i*39,columnW,label,person.skills[i],p));meter(this,pad,contentY+279,columnW,'EXPÉRIENCE · niveau de test 3',uiState.xp,p.gold,p);}
 else if(uiState.tab===1){text(this,pad,contentY,'PROGRAMME DE DÉMONSTRATION',12,p.muted,true);const entries=[['08:00','Départ du bureau','Trajet'],['08:30',person.action,person.location],['10:00','Retour au bureau','Bilan']];entries.forEach(([hour,title,sub],i)=>{const y=contentY+30+i*68;panel(this,pad,y,columnW,60,p);text(this,pad+12,y+9,hour,12,p.muted);text(this,pad+72,y+9,title,14,p.ink,true);text(this,pad+72,y+32,sub,12,p.muted);});text(this,pad,contentY+250,'Horaires fictifs · aucun ordre réel exécuté.',12,p.muted);button(this,pad,contentY+278,columnW,uiState.playing?'Pause de la progression':'Animer la progression',()=>{uiState.playing=!uiState.playing;this.changed();},{p,selected:uiState.playing,disabled:uiState.disabled});}
 else{const docs=['Rapport de terrain','Équipement','Notes personnelles'];docs.forEach((name,i)=>button(this,pad,contentY+i*48,columnW,name,()=>{uiState.document=i;uiState.modal=true;this.draw();},{p}));text(this,pad,contentY+167,'DERNIÈRES ENTRÉES',12,p.muted,true);text(this,pad,contentY+195,'08:42  ·  Position confirmée\n08:30  ·  Début de l’action\n08:00  ·  Départ du bureau',14,p.ink).setLineSpacing(12);}
 const actionY=compact?765:418;panel(this,rx,actionY,columnW,157,p);text(this,rx+14,actionY+12,uiState.busy?'ACTION EN COURS':'ACTION EN ATTENTE',12,p.muted,true);const cx=rx+61,cy=actionY+84;actionPie(this,cx,cy,37,uiState.progress,uiState.sector,p,i=>{uiState.sector=i;this.changed();});text(this,rx+119,actionY+43,person.action,17,p.ink,true);text(this,rx+119,actionY+73,sectors[uiState.sector].name,14,p.muted);text(this,rx+119,actionY+97,'Toucher un secteur',11,p.muted);text(this,rx+14,actionY+135,'Trajet 25 % · Action 50 % · Retour 25 %',10,p.muted);
 const miniY=actionY+172;minimap(this,rx,miniY,columnW,compact?167:160,p,place=>{uiState.toast=place;this.draw();this.game.events.emit('selection',place);});
 if(!compact)button(this,pad,752,columnW,'Ouvrir le dossier complet',()=>{uiState.modal=true;this.draw();},{p});
 else button(this,pad,1130,inner,'Ouvrir le dossier complet',()=>{uiState.modal=true;this.draw();},{p});
 if(uiState.toast){text(this,rx+12,miniY+130,uiState.toast,12,p.ink,true).setBackgroundColor(uiState.theme==='night'?'#243440':'#f2ecdf');}
 if(uiState.modal)this.modal(w,h,p);
 }
 modal(w:number,h:number,p:typeof palettes.night){const pad=16,mw=Math.min(480,w-32),mh=355,mx=(w-mw)/2;const canvas=this.game.canvas.getBoundingClientRect();const top=Math.max(10,(Math.max(0,-canvas.top)+24));const my=Math.min(h-mh-14,top);this.add.rectangle(0,0,w,h,0x050b10,.75).setOrigin(0).setInteractive();const c=this.add.container(mx,my),person=profiles[uiState.selected],bar=this.add.rectangle(0,0,mw,48,p.line).setOrigin(0).setInteractive({draggable:true,useHandCursor:true});c.add([this.add.rectangle(0,0,mw,mh,p.panel).setOrigin(0).setStrokeStyle(1,p.gold),bar,text(this,16,16,'DOSSIER / '+person.name.toUpperCase(),12,p.ink,true)]);const titles=['Rapport de terrain','Équipement','Notes personnelles'];c.add(text(this,pad,70,titles[uiState.document],21,p.ink,true));const body=uiState.document===0?`Localisation : ${person.location}\nActivité : ${person.action}\nÉnergie : ${Math.round(uiState.energy)} %\nProgression : ${Math.round(uiState.progress)} %\n\nRapport fictif pour tester la fiche.`:uiState.document===1?'Arme : revolver de démonstration\nVéhicule : voiture de l’équipe\nDossier : documents de mission\n\nAucun inventaire ni bonus appliqué.':person.note;c.add(text(this,pad,108,body,14,p.ink).setWordWrapWidth(mw-32).setLineSpacing(9));c.add(button(this,pad,mh-58,mw-32,'Fermer',()=>{uiState.modal=false;this.draw();},{p,selected:true}));this.input.setDraggable(bar);let start={x:mx,y:my,px:0,py:0};bar.on('dragstart',(pointer:Phaser.Input.Pointer)=>{start={x:c.x,y:c.y,px:pointer.x,py:pointer.y};});bar.on('drag',(pointer:Phaser.Input.Pointer)=>{c.x=Phaser.Math.Clamp(start.x+(pointer.x-start.px)/density(),0,w-mw);c.y=Phaser.Math.Clamp(start.y+(pointer.y-start.py)/density(),0,h-mh);});}
 update(_t:number,dt:number){if(!uiState.playing||uiState.modal||uiState.disabled)return;this.elapsed+=dt;if(this.elapsed<250)return;uiState.progress=clampPercent(uiState.progress+this.elapsed/1000*5);this.elapsed=0;if(uiState.progress===100)uiState.playing=false;this.changed();}
}
