import Phaser from 'phaser';
import {Palette,text,panel} from './theme';
import {clampPercent} from './ui-fixture';
import {density} from './display';
export function meter(scene:Phaser.Scene,x:number,y:number,w:number,label:string,value:number,color:number,p:Palette){const v=clampPercent(value);text(scene,x,y,label,13,p.muted);text(scene,x+w,y,`${Math.round(v)} %`,13,p.ink,true).setOrigin(1,0);scene.add.rectangle(x,y+24,w,8,p.line).setOrigin(0);scene.add.rectangle(x,y+24,w*v/100,8,color).setOrigin(0);}
export function skill(scene:Phaser.Scene,x:number,y:number,w:number,label:string,value:number,p:Palette){text(scene,x,y,label,14,p.ink);text(scene,x+w,y,`${value}/5`,13,p.muted).setOrigin(1,0);const sw=(w-20)/5;for(let i=0;i<5;i++)scene.add.rectangle(x+i*(sw+5),y+24,sw,7,i<value?p.gold:p.line).setOrigin(0);}
export const sectors=[{name:'Trajet',portion:.25,color:0x859ba4},{name:'Action',portion:.5,color:0xd4b271},{name:'Retour',portion:.25,color:0x6caaa0}];
export function actionPie(scene:Phaser.Scene,cx:number,cy:number,r:number,progress:number,selected:number,p:Palette,onSelect:(i:number)=>void){const g=scene.add.graphics();let start=-Math.PI/2;sectors.forEach((s,i)=>{const end=start+s.portion*Math.PI*2;g.fillStyle(s.color,i===selected?1:.58);g.beginPath().moveTo(cx,cy).arc(cx,cy,r,start,end,false).closePath().fillPath();g.lineStyle(2,p.panel).beginPath().moveTo(cx,cy).lineTo(cx+Math.cos(start)*r,cy+Math.sin(start)*r).strokePath();start=end;});g.fillStyle(p.panel).fillCircle(cx,cy,r*.58);g.lineStyle(3,p.gold).beginPath().arc(cx,cy,r+5,-Math.PI/2,-Math.PI/2+clampPercent(progress)/100*Math.PI*2,false).strokePath();text(scene,cx,cy,`${Math.round(progress)}%`,15,p.ink,true).setOrigin(.5);scene.add.circle(cx,cy,r+8,0,0).setInteractive({useHandCursor:true}).on('pointerup',(pointer:Phaser.Input.Pointer)=>{if(pointer.getDistance()>10*density())return;const world=scene.cameras.main.getWorldPoint(pointer.x,pointer.y);let t=(Math.atan2(world.y-cy,world.x-cx)+Math.PI/2+Math.PI*2)%(Math.PI*2)/(Math.PI*2);onSelect(t<.25?0:t<.75?1:2);});}
export function minimap(scene:Phaser.Scene,x:number,y:number,w:number,h:number,p:Palette,onSelect:(place:string)=>void){panel(scene,x,y,w,h,p);text(scene,x+14,y+12,'POSITION / QUARTIER',12,p.muted,true);const bx=x+14,by=y+39,bw=w-28,bh=h-54;const g=scene.add.graphics();g.fillStyle(0x17272f).fillRect(bx,by,bw,bh);g.lineStyle(14,0x6c7b7d).beginPath().moveTo(bx+bw*.5,by).lineTo(bx+bw*.5,by+bh).moveTo(bx,by+bh*.48).lineTo(bx+bw,by+bh*.48).strokePath();g.lineStyle(2,0xe4bc73).beginPath().moveTo(bx+bw*.3,by+bh*.3).lineTo(bx+bw*.5,by+bh*.3).lineTo(bx+bw*.5,by+bh*.76).strokePath();const names=['Café Bellini','Garage Moreau','Hôtel du Port','Banque Centrale'];[[.23,.22],[.77,.22],[.23,.75],[.77,.75]].forEach(([a,b],i)=>{const px=bx+bw*a,py=by+bh*b;scene.add.rectangle(px,py,bw*.3,bh*.24,0x536970).setStrokeStyle(1,0x8c9991).setInteractive({useHandCursor:true}).on('pointerup',(pointer:Phaser.Input.Pointer)=>{if(pointer.getDistance()<=10*density())onSelect(names[i]);});text(scene,px,py,['QG','G','H','$'][i],12,'#e6d9bb',true).setOrigin(.5);});scene.add.circle(bx+bw*.5,by+bh*.32,5,0xf2cc82).setStrokeStyle(2,0xffffff);g.lineStyle(1,0xdfbf83,.7).strokeRect(bx+bw*.28,by+bh*.08,bw*.5,bh*.72);}
